language: c
dist: bionic
os:
  - linux
#  - osx
#  - windows
#osx_image: xcode11.3
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  jobs:
    - PYTHON_VERSION="3.8.3"
    - PYTHON_VERSION="3.7.7"
    - PYTHON_VERSION="3.6.10"
    - PYTHON_VERSION="3.5.9"
    - PYTHON_VERSION="3.9.0b1"
  global:
    - DEPLOY_BRANCHES: "'master'"
    - DEPLOY_PYTHONS: "'3.8.3'"
    - DEPLOY_OSES: "'linux'"
    - PYB_ARGS: "'-E ci -v -X analyze install'"
    - TWINE_USERNAME: repeatedly
    - secure: CpNaj4F3TZvpP1aSJWidh/XexrWODV2sBdObrYU79Gyh9hFl6WLsA3JM9BfVsy9cGb/P/jP6ly4Z0/6qdIzZ5D6FPOB1B7rn5GZ2LAMOypRCA6W2uJbRjUU373Wut0p0OmQcMPto6XJsMlpvOEq+1uAq+LLAnAGEmmYTeskZebs=

cache:
  directories:
    - $HOME/.pyenv

install: travis_wait 30 python travis/travis_shim.py install
script: travis_wait 60 python travis/travis_shim.py build
